import { EnvironmentProviders, importProvidersFrom } from '@angular/core';
import {
  ArrowLeftOutline,
  ArrowUpOutline,
  BulbOutline,
  CarOutline,
  CheckOutline,
  ClockCircleOutline,
  CloseOutline,
  CloudOutline,
  EditOutline,
  EyeOutline,
  GithubOutline,
  HeartFill,
  HeartOutline,
  HomeOutline,
  InfoCircleOutline,
  LeftOutline,
  LinkOutline,
  MailOutline,
  MenuOutline,
  MessageOutline,
  NotificationOutline,
  QqOutline,
  RightOutline,
  SearchOutline,
  SmileOutline,
  ToolOutline,
  UserOutline,
  WechatOutline,
  ZhihuOutline,
} from '@ant-design/icons-angular/icons';
import { IconDefinition } from '@ant-design/icons-angular';
import { NzIconModule } from 'ng-zorro-antd/icon';

const icons: IconDefinition[] = [
  ArrowLeftOutline,
  ArrowUpOutline,
  BulbOutline,
  CarOutline,
  CheckOutline,
  ClockCircleOutline,
  CloseOutline,
  CloudOutline,
  EditOutline,
  EyeOutline,
  GithubOutline,
  HeartFill,
  HeartOutline,
  HomeOutline,
  InfoCircleOutline,
  LeftOutline,
  LinkOutline,
  MailOutline,
  MenuOutline,
  MessageOutline,
  NotificationOutline,
  QqOutline,
  RightOutline,
  SearchOutline,
  SmileOutline,
  ToolOutline,
  UserOutline,
  WechatOutline,
  ZhihuOutline,
];

export function provideNzIcons(): EnvironmentProviders {
  return importProvidersFrom(NzIconModule.forRoot(icons));
}
