import { environment } from '../../environments/environment';

export const API = {
  BASE_URL: environment.apiBaseUrl,

  BLOG: '/blog',
  BLOG_RELATED: '/blog/related',
  TAG: '/blog/tag',
  INFO: '/site/visit',
  VISIT_DWELL: '/site/visit/dwell',
  SITE_INFO: '/site/info',
  ANNOUNCEMENT_CURRENT: '/announcement/current',
  ABOUT_CURRENT: '/about/current',
  DAY_INFO: '/blog/info',
  LIFE: '/life',
  LIFE_YEAR: '/life/years',
  LIFE_TAG: '/life/tag',
  CAPTCHA: '/site/captcha',
  MESSAGE: '/site/message',
  BOOK: '/world/book',
  BOOK_LIST: '/world/book/list',
  GAME: '/world/game',
  GAME_LIST: '/world/game/list',
  EQUIPMENT_LIST: '/equipment/list',
  QUESTION: '/question',
  MODULE: '/module',
  LINK: '/site/link',
  LINK_ARTICLES: '/site/link/articles',
  GITHUB_CONTRIBUTIONS: '/github/contributions',
};
